//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTS.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTS.Localization.Resources.DisplayAttribute.DisplayRes", typeof(DisplayRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна адреси електронної пошти є простим, двоступеневий процесом. Вкажіть нову адресу електронної пошти, яку ви хочете використовувати, і ми надішлемо вам на поточну адресу лист для того щоб підтвердити та завершити зміну адреси..
        /// </summary>
        public static string ChangeEmailDescription {
            get {
                return ResourceManager.GetString("ChangeEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть пароль*.
        /// </summary>
        public static string ConfirmPasswordName {
            get {
                return ResourceManager.GetString("ConfirmPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміст.
        /// </summary>
        public static string ContentName {
            get {
                return ResourceManager.GetString("ContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукова ступінь.
        /// </summary>
        public static string DegreeName {
            get {
                return ResourceManager.GetString("DegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес електронної пошти*.
        /// </summary>
        public static string EmailAddressName {
            get {
                return ResourceManager.GetString("EmailAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        public static string EmailName {
            get {
                return ResourceManager.GetString("EmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача або адрес електронної пошти.
        /// </summary>
        public static string EmailOrUserNameName {
            get {
                return ResourceManager.GetString("EmailOrUserNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook URL-адреса.
        /// </summary>
        public static string FacebookName {
            get {
                return ResourceManager.GetString("FacebookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повне ім&apos;я*.
        /// </summary>
        public static string FullNameName {
            get {
                return ResourceManager.GetString("FullNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привітання.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect URL-адреса.
        /// </summary>
        public static string IntellectName {
            get {
                return ResourceManager.GetString("IntellectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень : .
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль*.
        /// </summary>
        public static string NewPasswordName {
            get {
                return ResourceManager.GetString("NewPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старий пароль*.
        /// </summary>
        public static string OldPasswordName {
            get {
                return ResourceManager.GetString("OldPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач.
        /// </summary>
        public static string PairTeacherIdName {
            get {
                return ResourceManager.GetString("PairTeacherIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль*.
        /// </summary>
        public static string PasswordName {
            get {
                return ResourceManager.GetString("PasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографія.
        /// </summary>
        public static string PhotoName {
            get {
                return ResourceManager.GetString("PhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада*.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ранг.
        /// </summary>
        public static string RankName {
            get {
                return ResourceManager.GetString("RankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам&apos;ятати мене.
        /// </summary>
        public static string RememberMeName {
            get {
                return ResourceManager.GetString("RememberMeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ролі облікового запису.
        /// </summary>
        public static string RolesName {
            get {
                return ResourceManager.GetString("RolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати підтвердження.
        /// </summary>
        public static string SendVerificationName {
            get {
                return ResourceManager.GetString("SendVerificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слаг.
        /// </summary>
        public static string SlugName {
            get {
                return ResourceManager.GetString("SlugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діапазон дат : .
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок*.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter URL-адреса.
        /// </summary>
        public static string TwitterName {
            get {
                return ResourceManager.GetString("TwitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете змінити ім&apos;я користувача, який впливає на те як ви входите в систему..
        /// </summary>
        public static string UserNameDescription {
            get {
                return ResourceManager.GetString("UserNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача*.
        /// </summary>
        public static string UserNameName {
            get {
                return ResourceManager.GetString("UserNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача.
        /// </summary>
        public static string UserNameShortName {
            get {
                return ResourceManager.GetString("UserNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вконтакті URL-адреса.
        /// </summary>
        public static string VkontakteName {
            get {
                return ResourceManager.GetString("VkontakteName", resourceCulture);
            }
        }
    }
}
