//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTS.UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTS.UI.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про кафедру.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про кафедру.
        /// </summary>
        public static string AboutDepartment {
            get {
                return ResourceManager.GetString("AboutDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досягнення.
        /// </summary>
        public static string Achievments {
            get {
                return ResourceManager.GetString("Achievments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;яви.
        /// </summary>
        public static string Advertisment {
            get {
                return ResourceManager.GetString("Advertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курси та стажування.
        /// </summary>
        public static string CoursesAndProbations {
            get {
                return ResourceManager.GetString("CoursesAndProbations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенту.
        /// </summary>
        public static string ForStudent {
            get {
                return ResourceManager.GetString("ForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія кафедри.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматика і Управління в Технічних Системах (АУТС).
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторії.
        /// </summary>
        public static string Laboratories {
            get {
                return ResourceManager.GetString("Laboratories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наші випускники.
        /// </summary>
        public static string OurGraduates {
            get {
                return ResourceManager.GetString("OurGraduates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Працевлаштування.
        /// </summary>
        public static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аспірантура.
        /// </summary>
        public static string Postgraduate {
            get {
                return ResourceManager.GetString("Postgraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премії та винагороди.
        /// </summary>
        public static string PrizeAndAwards {
            get {
                return ResourceManager.GetString("PrizeAndAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дослідження.
        /// </summary>
        public static string Researches {
            get {
                return ResourceManager.GetString("Researches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наука.
        /// </summary>
        public static string Science {
            get {
                return ResourceManager.GetString("Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукові зв&apos;язки.
        /// </summary>
        public static string ScienceConnections {
            get {
                return ResourceManager.GetString("ScienceConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукові напрями.
        /// </summary>
        public static string ScienceFields {
            get {
                return ResourceManager.GetString("ScienceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допоміжний персонал.
        /// </summary>
        public static string ServicePersonell {
            get {
                return ResourceManager.GetString("ServicePersonell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад сессії.
        /// </summary>
        public static string SessionSchedule {
            get {
                return ResourceManager.GetString("SessionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спеціальності.
        /// </summary>
        public static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг студентів.
        /// </summary>
        public static string StudentRating {
            get {
                return ResourceManager.GetString("StudentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Педагогічний склад.
        /// </summary>
        public static string TeachingStaff {
            get {
                return ResourceManager.GetString("TeachingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисні посилання.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
    }
}
