//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTS.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTS.Localization.Resources.GlobalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про кафедру.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про кафедру.
        /// </summary>
        public static string AboutDepartment {
            get {
                return ResourceManager.GetString("AboutDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обліковий запис.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цей обліковий запис був заблокований. Спробуйте ще раз пізніше..
        /// </summary>
        public static string AccountLockedMsg {
            get {
                return ResourceManager.GetString("AccountLockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Облікові записи.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Досягнення.
        /// </summary>
        public static string Achievments {
            get {
                return ResourceManager.GetString("Achievments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дії.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АУТС.
        /// </summary>
        public static string ACTS {
            get {
                return ResourceManager.GetString("ACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адміністрування.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на адміністратор сайту АУТС.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;яви.
        /// </summary>
        public static string Advertisment {
            get {
                return ResourceManager.GetString("Advertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Застосувати фільтр.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви впевнені, що хочете зробити це?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блог.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати пост.
        /// </summary>
        public static string BlogAddPost {
            get {
                return ResourceManager.GetString("BlogAddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати .
        /// </summary>
        public static string BlogEdit {
            get {
                return ResourceManager.GetString("BlogEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профіль.
        /// </summary>
        public static string BlogEditProfile {
            get {
                return ResourceManager.GetString("BlogEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основні Інтереси.
        /// </summary>
        public static string BlogInterests {
            get {
                return ResourceManager.GetString("BlogInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Головна.
        /// </summary>
        public static string BlogMain {
            get {
                return ResourceManager.GetString("BlogMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матеріали для студентів.
        /// </summary>
        public static string BlogMaterials {
            get {
                return ResourceManager.GetString("BlogMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекти.
        /// </summary>
        public static string BlogProjects {
            get {
                return ResourceManager.GetString("BlogProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основні публікації.
        /// </summary>
        public static string BlogPublications {
            get {
                return ResourceManager.GetString("BlogPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити пост.
        /// </summary>
        public static string BlogRemovePost {
            get {
                return ResourceManager.GetString("BlogRemovePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місце виклику.
        /// </summary>
        public static string CallSite {
            get {
                return ResourceManager.GetString("CallSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відмінити.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відмінити та повернутися до таблиці.
        /// </summary>
        public static string CancelAndReturnToTable {
            get {
                return ResourceManager.GetString("CancelAndReturnToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви не можете видалити себе тут, перейдіть в розділ &quot;Мій рахунок&quot; для цього..
        /// </summary>
        public static string CanNotDeleteHimSelfHere {
            get {
                return ResourceManager.GetString("CanNotDeleteHimSelfHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви не можете видалити єдиного користувача з правами адміністратора..
        /// </summary>
        public static string CanNotDeleteOnlyAdminUser {
            get {
                return ResourceManager.GetString("CanNotDeleteOnlyAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви успішно змінили свою електронну пошту на &quot;{0}&quot;..
        /// </summary>
        public static string ChangedEmailMsg {
            get {
                return ResourceManager.GetString("ChangedEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви успішно змінили свій пароль..
        /// </summary>
        public static string ChangedPasswordMsg {
            get {
                return ResourceManager.GetString("ChangedPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви успішно змінили своє ім&apos;я користувача з &quot;{0}&quot; на &quot;{1}&quot;..
        /// </summary>
        public static string ChangedUserNameMsg {
            get {
                return ResourceManager.GetString("ChangedUserNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити електронну пошту.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити ім&apos;я користувача.
        /// </summary>
        public static string ChangeUserName {
            get {
                return ResourceManager.GetString("ChangeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірте свою електронну пошту.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вимоги до вступу.
        /// </summary>
        public static string ConditionsOfAdmissions {
            get {
                return ResourceManager.GetString("ConditionsOfAdmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для підтвердження надрукуйте.
        /// </summary>
        public static string ConfirmationPhraseLabelPart1 {
            get {
                return ResourceManager.GetString("ConfirmationPhraseLabelPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  нижче:.
        /// </summary>
        public static string ConfirmationPhraseLabelPart2 {
            get {
                return ResourceManager.GetString("ConfirmationPhraseLabelPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтвердити пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакти.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміст.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курси та стажування.
        /// </summary>
        public static string CoursesAndProbations {
            get {
                return ResourceManager.GetString("CoursesAndProbations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити обліковий запис.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створено.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити робітника.
        /// </summary>
        public static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити подію.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити новий обліковий запис.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити нового робітника.
        /// </summary>
        public static string CreateNewEmployee {
            get {
                return ResourceManager.GetString("CreateNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити нову подію.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити нову новину.
        /// </summary>
        public static string CreateNewNews {
            get {
                return ResourceManager.GetString("CreateNewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити новину.
        /// </summary>
        public static string CreateNews {
            get {
                return ResourceManager.GetString("CreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити нового викладача.
        /// </summary>
        public static string CreateNewTeacher {
            get {
                return ResourceManager.GetString("CreateNewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити викладача.
        /// </summary>
        public static string CreateTeacher {
            get {
                return ResourceManager.GetString("CreateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на uk.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поточна фотографія.
        /// </summary>
        public static string CurrentPhoto {
            get {
                return ResourceManager.GetString("CurrentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Майстерня.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~/bundles/datatables-uk.
        /// </summary>
        public static string dataTablePath {
            get {
                return ResourceManager.GetString("dataTablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~/bundles/daterange-uk.
        /// </summary>
        public static string dateRangePath {
            get {
                return ResourceManager.GetString("dateRangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ступінь.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити обліковий запис.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будьте обережні, видалений обліковий запис неможливо відновити..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити цей обліковий запис.
        /// </summary>
        public static string DeleteThisAccount {
            get {
                return ResourceManager.GetString("DeleteThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити ваш обліковий запис.
        /// </summary>
        public static string DeleteYourAccount {
            get {
                return ResourceManager.GetString("DeleteYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробиці.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати обліковий запис.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати робітника.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати подію.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати новину.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати викладача.
        /// </summary>
        public static string EditTeacher {
            get {
                return ResourceManager.GetString("EditTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Електронна пошта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса електронної пошти не змінена. Не можна використовувати ваш поточний адрес для її зміни..
        /// </summary>
        public static string EmailNotChangedErrMsg {
            get {
                return ResourceManager.GetString("EmailNotChangedErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я користувача або адресу електронної пошти.
        /// </summary>
        public static string EmailOrUserName {
            get {
                return ResourceManager.GetString("EmailOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робітник.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робітник &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string EmployeeCreatedMsg {
            get {
                return ResourceManager.GetString("EmployeeCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робітник &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string EmployeeDeletedMsg {
            get {
                return ResourceManager.GetString("EmployeeDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робітники.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Робітник &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string EmployeeSavedMsg {
            get {
                return ResourceManager.GetString("EmployeeSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англійська.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подія.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подія з заголовком &quot;{0}&quot; успішно створена..
        /// </summary>
        public static string EventCreatedMsg {
            get {
                return ResourceManager.GetString("EventCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подія з заголовком &quot;{0}&quot; успішно видалена..
        /// </summary>
        public static string EventDeletedMsg {
            get {
                return ResourceManager.GetString("EventDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Події.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подія з заголовком &quot;{0}&quot; успішно збережена..
        /// </summary>
        public static string EventSavedMsg {
            get {
                return ResourceManager.GetString("EventSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Facebook URL-адреса.
        /// </summary>
        public static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви не змогли змінити адресу електронної пошти на &quot;{0}&quot;. {1} Можливо, це сталося через закінчення відведених 6 годин для виконання операції..
        /// </summary>
        public static string FailedChangeEmailMsg {
            get {
                return ResourceManager.GetString("FailedChangeEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невдала спроба входу..
        /// </summary>
        public static string FailedLoginAttemptsMsg {
            get {
                return ResourceManager.GetString("FailedLoginAttemptsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довузівська підготовка.
        /// </summary>
        public static string FDP {
            get {
                return ResourceManager.GetString("FDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~/bundles/fileinput-uk.
        /// </summary>
        public static string fileinputPath {
            get {
                return ResourceManager.GetString("fileinputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абітурієнту.
        /// </summary>
        public static string ForEnrollee {
            get {
                return ResourceManager.GetString("ForEnrollee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забули пароль.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ми тільки що відправили Вам лист з посиланням для скидання пароля!.
        /// </summary>
        public static string ForgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть адресу електронної пошти, і ми надішлемо вам посилання для відновлення пароля.
        /// </summary>
        public static string ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забули пароль?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студенту.
        /// </summary>
        public static string ForStudent {
            get {
                return ResourceManager.GetString("ForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повне ім&apos;я.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Історія кафедри.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Головна.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматика і Управління в Технічних Системах (АУТС).
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Індифікатор.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я забув свій пароль.
        /// </summary>
        public static string IForgotMyPassword {
            get {
                return ResourceManager.GetString("IForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зображення.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невірний ім&apos;я (емейл) користувача або пароль..
        /// </summary>
        public static string IncorrectUserNameOrPasswordMsg {
            get {
                return ResourceManager.GetString("IncorrectUserNameOrPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ця сторінка в розробці..
        /// </summary>
        public static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intellect URL-адреса.
        /// </summary>
        public static string IntellectUrl {
            get {
                return ResourceManager.GetString("IntellectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Є активною.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КПІ.
        /// </summary>
        public static string KPI {
            get {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лабораторії.
        /// </summary>
        public static string Laboratories {
            get {
                return ResourceManager.GetString("Laboratories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рівень.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логувальник.
        /// </summary>
        public static string Logger {
            get {
                return ResourceManager.GetString("Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логування.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увійти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увійдіть, щоб почати сеанс.
        /// </summary>
        public static string LoginMsg {
            get {
                return ResourceManager.GetString("LoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вийти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магістратура.
        /// </summary>
        public static string Magistracy {
            get {
                return ResourceManager.GetString("Magistracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Головна.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модифіковано.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Особистий кабінет.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАВІГАЦІЯ.
        /// </summary>
        public static string NAVIGATION {
            get {
                return ResourceManager.GetString("NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новий пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новина.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новина з заголовком &quot;{0}&quot; успішно створена..
        /// </summary>
        public static string NewsCreatedMsg {
            get {
                return ResourceManager.GetString("NewsCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новина з заголовком &quot;{0}&quot; успішно видалена..
        /// </summary>
        public static string NewsDeletedMsg {
            get {
                return ResourceManager.GetString("NewsDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новина з заголовком &quot;{0}&quot; успішно збережена..
        /// </summary>
        public static string NewsSavedMsg {
            get {
                return ResourceManager.GetString("NewsSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Немає.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бракує прав для поточного облікового запису..
        /// </summary>
        public static string NotEnoughRightsMsg {
            get {
                return ResourceManager.GetString("NotEnoughRightsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На Головній.
        /// </summary>
        public static string OnMain {
            get {
                return ResourceManager.GetString("OnMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дні відкритих дверей.
        /// </summary>
        public static string OpenDoors {
            get {
                return ResourceManager.GetString("OpenDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наші випускники.
        /// </summary>
        public static string OurGraduates {
            get {
                return ResourceManager.GetString("OurGraduates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Персональна сторінка.
        /// </summary>
        public static string PersonalPage {
            get {
                return ResourceManager.GetString("PersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Працевлаштування.
        /// </summary>
        public static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посада.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аспірантура.
        /// </summary>
        public static string Postgraduate {
            get {
                return ResourceManager.GetString("Postgraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Премії та винагороди.
        /// </summary>
        public static string PrizeAndAwards {
            get {
                return ResourceManager.GetString("PrizeAndAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагування.
        /// </summary>
        public static string Redact {
            get {
                return ResourceManager.GetString("Redact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дослідження.
        /// </summary>
        public static string Researches {
            get {
                return ResourceManager.GetString("Researches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скидання пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть свій пароль.
        /// </summary>
        public static string ResetPasswordMsg {
            get {
                return ResourceManager.GetString("ResetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ролі.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Російська.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розклад.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наука.
        /// </summary>
        public static string Science {
            get {
                return ResourceManager.GetString("Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наукові зв&apos;язки.
        /// </summary>
        public static string ScienceConnections {
            get {
                return ResourceManager.GetString("ScienceConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наукові напрями.
        /// </summary>
        public static string ScienceFields {
            get {
                return ResourceManager.GetString("ScienceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наукові інтереси.
        /// </summary>
        public static string ScienceInterests {
            get {
                return ResourceManager.GetString("ScienceInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошук....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відправити лист.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ми надіслали лист з підтвердженням на {0}. Будь ласка, дотримуйтесь інструкцій в листі..
        /// </summary>
        public static string SendVerificationEmailMsg {
            get {
                return ResourceManager.GetString("SendVerificationEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допоміжний персонал.
        /// </summary>
        public static string ServicePersonell {
            get {
                return ResourceManager.GetString("ServicePersonell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розклад сессії.
        /// </summary>
        public static string SessionSchedule {
            get {
                return ResourceManager.GetString("SessionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увійти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слаг.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слаг є частиною URL, який ідентифікує сторінки за допомогою легких для читання ключових слів..
        /// </summary>
        public static string SlugHelpText {
            get {
                return ResourceManager.GetString("SlugHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соціальні посилання.
        /// </summary>
        public static string SocialLinks {
            get {
                return ResourceManager.GetString("SocialLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спеціальності.
        /// </summary>
        public static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трасування стека.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейтинг студентів.
        /// </summary>
        public static string StudentRating {
            get {
                return ResourceManager.GetString("StudentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиця облікових записів.
        /// </summary>
        public static string TableOfAccounts {
            get {
                return ResourceManager.GetString("TableOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиця робітників.
        /// </summary>
        public static string TableOfEmployees {
            get {
                return ResourceManager.GetString("TableOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиця подій.
        /// </summary>
        public static string TableOfEvent {
            get {
                return ResourceManager.GetString("TableOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиця новин.
        /// </summary>
        public static string TableOfNews {
            get {
                return ResourceManager.GetString("TableOfNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиця викладачів.
        /// </summary>
        public static string TableOfTeachers {
            get {
                return ResourceManager.GetString("TableOfTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблиці.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладач.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладач відсутій.
        /// </summary>
        public static string TeacherAbsent {
            get {
                return ResourceManager.GetString("TeacherAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладач з ім&apos;ям &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string TeacherCreatedMsg {
            get {
                return ResourceManager.GetString("TeacherCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладач з ім&apos;ям &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string TeacherDeletedMsg {
            get {
                return ResourceManager.GetString("TeacherDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладачі.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Викладач з ім&apos;ям &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string TeacherSavedMsg {
            get {
                return ResourceManager.GetString("TeacherSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Педагогічний склад.
        /// </summary>
        public static string TeachingStaff {
            get {
                return ResourceManager.GetString("TeachingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часовий діапазон.
        /// </summary>
        public static string TimeRange {
            get {
                return ResourceManager.GetString("TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~/bundles/tinymce-uk.
        /// </summary>
        public static string tinymcePath {
            get {
                return ResourceManager.GetString("tinymcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitter URL-адреса.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Українська.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новини.
        /// </summary>
        public static string Uncos {
            get {
                return ResourceManager.GetString("Uncos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновити електронну пошту.
        /// </summary>
        public static string UpdateEmail {
            get {
                return ResourceManager.GetString("UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновити пароль.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновити ім&apos;я користувача.
        /// </summary>
        public static string UpdateUserName {
            get {
                return ResourceManager.GetString("UpdateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантажити нову картинку.
        /// </summary>
        public static string UploadNewImage {
            get {
                return ResourceManager.GetString("UploadNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантажити нову фотографію.
        /// </summary>
        public static string UploadNewPhoto {
            get {
                return ResourceManager.GetString("UploadNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корисні посилання.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Користувач &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string UserCreatedMsg {
            get {
                return ResourceManager.GetString("UserCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Користувач &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string UserDeletedMsg {
            get {
                return ResourceManager.GetString("UserDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я користувача.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таке ім&apos;я користувача вже існує. Будь ласка, введіть інше ім&apos;я..
        /// </summary>
        public static string UserNameExistErrMsg {
            get {
                return ResourceManager.GetString("UserNameExistErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я користувача не змінено. Не можна використовувати ваше поточне ім&apos;я користувача для його зміни..
        /// </summary>
        public static string UserNameNotChangedErrMsg {
            get {
                return ResourceManager.GetString("UserNameNotChangedErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Користувач з індифікатором = {0} не знайдений..
        /// </summary>
        public static string UserNoFound {
            get {
                return ResourceManager.GetString("UserNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Користувач &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string UserSavedMsg {
            get {
                return ResourceManager.GetString("UserSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версія.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вконтакті URL-адреса.
        /// </summary>
        public static string VkontakteUrl {
            get {
                return ResourceManager.GetString("VkontakteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
