//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTS.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTS.Localization.Resources.GlobalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про кафедру.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про кафедру.
        /// </summary>
        public static string AboutDepartment {
            get {
                return ResourceManager.GetString("AboutDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей обліковий запис був заблокований. Спробуйте ще раз пізніше..
        /// </summary>
        public static string AccountLockedMsg {
            get {
                return ResourceManager.GetString("AccountLockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Облікові записи.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досягнення.
        /// </summary>
        public static string Achievments {
            get {
                return ResourceManager.GetString("Achievments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дії.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АУТС.
        /// </summary>
        public static string ACTS {
            get {
                return ResourceManager.GetString("ACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адміністрування.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to адміністратор сайту АУТС.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;яви.
        /// </summary>
        public static string Advertisment {
            get {
                return ResourceManager.GetString("Advertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Застосувати фільтр.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете зробити це?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блог.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати пост.
        /// </summary>
        public static string BlogAddPost {
            get {
                return ResourceManager.GetString("BlogAddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати .
        /// </summary>
        public static string BlogEdit {
            get {
                return ResourceManager.GetString("BlogEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        public static string BlogEditProfile {
            get {
                return ResourceManager.GetString("BlogEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основні Інтереси.
        /// </summary>
        public static string BlogInterests {
            get {
                return ResourceManager.GetString("BlogInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string BlogMain {
            get {
                return ResourceManager.GetString("BlogMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріали для студентів.
        /// </summary>
        public static string BlogMaterials {
            get {
                return ResourceManager.GetString("BlogMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекти.
        /// </summary>
        public static string BlogProjects {
            get {
                return ResourceManager.GetString("BlogProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основні публікації.
        /// </summary>
        public static string BlogPublications {
            get {
                return ResourceManager.GetString("BlogPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити пост.
        /// </summary>
        public static string BlogRemovePost {
            get {
                return ResourceManager.GetString("BlogRemovePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце виклику.
        /// </summary>
        public static string CallSite {
            get {
                return ResourceManager.GetString("CallSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити та повернутися до таблиці.
        /// </summary>
        public static string CancelAndReturnToTable {
            get {
                return ResourceManager.GetString("CancelAndReturnToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не можете видалити себе тут, перейдіть в розділ &quot;Мій рахунок&quot; для цього..
        /// </summary>
        public static string CanNotDeleteHimSelfHere {
            get {
                return ResourceManager.GetString("CanNotDeleteHimSelfHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не можете видалити єдиного користувача з правами адміністратора..
        /// </summary>
        public static string CanNotDeleteOnlyAdminUser {
            get {
                return ResourceManager.GetString("CanNotDeleteOnlyAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви успішно змінили свою електронну пошту на &quot;{0}&quot;..
        /// </summary>
        public static string ChangedEmailMsg {
            get {
                return ResourceManager.GetString("ChangedEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви успішно змінили свій пароль..
        /// </summary>
        public static string ChangedPasswordMsg {
            get {
                return ResourceManager.GetString("ChangedPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви успішно змінили своє ім&apos;я користувача з &quot;{0}&quot; на &quot;{1}&quot;..
        /// </summary>
        public static string ChangedUserNameMsg {
            get {
                return ResourceManager.GetString("ChangedUserNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити електронну пошту.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити ім&apos;я користувача.
        /// </summary>
        public static string ChangeUserName {
            get {
                return ResourceManager.GetString("ChangeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірте свою електронну пошту.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вимоги до вступу.
        /// </summary>
        public static string ConditionsOfAdmissions {
            get {
                return ResourceManager.GetString("ConditionsOfAdmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для підтвердження надрукуйте.
        /// </summary>
        public static string ConfirmationPhraseLabelPart1 {
            get {
                return ResourceManager.GetString("ConfirmationPhraseLabelPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  нижче:.
        /// </summary>
        public static string ConfirmationPhraseLabelPart2 {
            get {
                return ResourceManager.GetString("ConfirmationPhraseLabelPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміст.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курси та стажування.
        /// </summary>
        public static string CoursesAndProbations {
            get {
                return ResourceManager.GetString("CoursesAndProbations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити обліковий запис.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створено.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити робітника.
        /// </summary>
        public static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити подію.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити новий обліковий запис.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нового робітника.
        /// </summary>
        public static string CreateNewEmployee {
            get {
                return ResourceManager.GetString("CreateNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нову подію.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нову новину.
        /// </summary>
        public static string CreateNewNews {
            get {
                return ResourceManager.GetString("CreateNewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити новину.
        /// </summary>
        public static string CreateNews {
            get {
                return ResourceManager.GetString("CreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити нового викладача.
        /// </summary>
        public static string CreateNewTeacher {
            get {
                return ResourceManager.GetString("CreateNewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити викладача.
        /// </summary>
        public static string CreateTeacher {
            get {
                return ResourceManager.GetString("CreateTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточна фотографія.
        /// </summary>
        public static string CurrentPhoto {
            get {
                return ResourceManager.GetString("CurrentPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майстерня.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bundles/datatables-uk.
        /// </summary>
        public static string dataTablePath {
            get {
                return ResourceManager.GetString("dataTablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bundles/daterange-uk.
        /// </summary>
        public static string dateRangePath {
            get {
                return ResourceManager.GetString("dateRangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ступінь.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити обліковий запис.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьте обережні, видалений обліковий запис неможливо відновити..
        /// </summary>
        public static string DeleteAccountDescription {
            get {
                return ResourceManager.GetString("DeleteAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити цей обліковий запис.
        /// </summary>
        public static string DeleteThisAccount {
            get {
                return ResourceManager.GetString("DeleteThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити ваш обліковий запис.
        /// </summary>
        public static string DeleteYourAccount {
            get {
                return ResourceManager.GetString("DeleteYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробиці.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисципліни.
        /// </summary>
        public static string Disciplines {
            get {
                return ResourceManager.GetString("Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати обліковий запис.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати робітника.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати подію.
        /// </summary>
        public static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати новину.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати викладача.
        /// </summary>
        public static string EditTeacher {
            get {
                return ResourceManager.GetString("EditTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса електронної пошти не змінена. Не можна використовувати ваш поточний адрес для її зміни..
        /// </summary>
        public static string EmailNotChangedErrMsg {
            get {
                return ResourceManager.GetString("EmailNotChangedErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача або адресу електронної пошти.
        /// </summary>
        public static string EmailOrUserName {
            get {
                return ResourceManager.GetString("EmailOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робітник.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робітник &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string EmployeeCreatedMsg {
            get {
                return ResourceManager.GetString("EmployeeCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робітник &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string EmployeeDeletedMsg {
            get {
                return ResourceManager.GetString("EmployeeDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робітники.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робітник &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string EmployeeSavedMsg {
            get {
                return ResourceManager.GetString("EmployeeSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подія.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подія з заголовком &quot;{0}&quot; успішно створена..
        /// </summary>
        public static string EventCreatedMsg {
            get {
                return ResourceManager.GetString("EventCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подія з заголовком &quot;{0}&quot; успішно видалена..
        /// </summary>
        public static string EventDeletedMsg {
            get {
                return ResourceManager.GetString("EventDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Події.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подія з заголовком &quot;{0}&quot; успішно збережена..
        /// </summary>
        public static string EventSavedMsg {
            get {
                return ResourceManager.GetString("EventSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook URL-адреса.
        /// </summary>
        public static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не змогли змінити адресу електронної пошти на &quot;{0}&quot;. {1} Можливо, це сталося через закінчення відведених 6 годин для виконання операції..
        /// </summary>
        public static string FailedChangeEmailMsg {
            get {
                return ResourceManager.GetString("FailedChangeEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невдала спроба входу..
        /// </summary>
        public static string FailedLoginAttemptsMsg {
            get {
                return ResourceManager.GetString("FailedLoginAttemptsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розповсюдженні запитання.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довузівська підготовка.
        /// </summary>
        public static string FDP {
            get {
                return ResourceManager.GetString("FDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bundles/fileinput-uk.
        /// </summary>
        public static string fileinputPath {
            get {
                return ResourceManager.GetString("fileinputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абітурієнту.
        /// </summary>
        public static string ForEnrollee {
            get {
                return ResourceManager.GetString("ForEnrollee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ми тільки що відправили Вам лист з посиланням для скидання пароля!.
        /// </summary>
        public static string ForgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть адресу електронної пошти, і ми надішлемо вам посилання для відновлення пароля.
        /// </summary>
        public static string ForgotPasswordMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенту.
        /// </summary>
        public static string ForStudent {
            get {
                return ResourceManager.GetString("ForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повне ім&apos;я.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія кафедри.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматика і Управління в Технічних Системах (АУТС).
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індифікатор.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я забув свій пароль.
        /// </summary>
        public static string IForgotMyPassword {
            get {
                return ResourceManager.GetString("IForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний ім&apos;я (емейл) користувача або пароль..
        /// </summary>
        public static string IncorrectUserNameOrPasswordMsg {
            get {
                return ResourceManager.GetString("IncorrectUserNameOrPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця сторінка в розробці..
        /// </summary>
        public static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect URL-адреса.
        /// </summary>
        public static string IntellectUrl {
            get {
                return ResourceManager.GetString("IntellectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Є активною.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПІ.
        /// </summary>
        public static string KPI {
            get {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лабораторії.
        /// </summary>
        public static string Laboratories {
            get {
                return ResourceManager.GetString("Laboratories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логувальник.
        /// </summary>
        public static string Logger {
            get {
                return ResourceManager.GetString("Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логування.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійдіть, щоб почати сеанс.
        /// </summary>
        public static string LoginMsg {
            get {
                return ResourceManager.GetString("LoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магістратура.
        /// </summary>
        public static string Magistracy {
            get {
                return ResourceManager.GetString("Magistracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модифіковано.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особистий кабінет.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАВІГАЦІЯ.
        /// </summary>
        public static string NAVIGATION {
            get {
                return ResourceManager.GetString("NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новина.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новина з заголовком &quot;{0}&quot; успішно створена..
        /// </summary>
        public static string NewsCreatedMsg {
            get {
                return ResourceManager.GetString("NewsCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новина з заголовком &quot;{0}&quot; успішно видалена..
        /// </summary>
        public static string NewsDeletedMsg {
            get {
                return ResourceManager.GetString("NewsDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новина з заголовком &quot;{0}&quot; успішно збережена..
        /// </summary>
        public static string NewsSavedMsg {
            get {
                return ResourceManager.GetString("NewsSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бракує прав для поточного облікового запису..
        /// </summary>
        public static string NotEnoughRightsMsg {
            get {
                return ResourceManager.GetString("NotEnoughRightsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Головній.
        /// </summary>
        public static string OnMain {
            get {
                return ResourceManager.GetString("OnMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дні відкритих дверей.
        /// </summary>
        public static string OpenDoors {
            get {
                return ResourceManager.GetString("OpenDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наші випускники.
        /// </summary>
        public static string OurGraduates {
            get {
                return ResourceManager.GetString("OurGraduates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональна сторінка.
        /// </summary>
        public static string PersonalPage {
            get {
                return ResourceManager.GetString("PersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Працевлаштування.
        /// </summary>
        public static string Placement {
            get {
                return ResourceManager.GetString("Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова публікація.
        /// </summary>
        public static string PostCreate {
            get {
                return ResourceManager.GetString("PostCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити публікацію.
        /// </summary>
        public static string PostDelete {
            get {
                return ResourceManager.GetString("PostDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати публікацію.
        /// </summary>
        public static string PostEdit {
            get {
                return ResourceManager.GetString("PostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аспірантура.
        /// </summary>
        public static string Postgraduate {
            get {
                return ResourceManager.GetString("Postgraduate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премії та винагороди.
        /// </summary>
        public static string PrizeAndAwards {
            get {
                return ResourceManager.GetString("PrizeAndAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування.
        /// </summary>
        public static string Redact {
            get {
                return ResourceManager.GetString("Redact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дослідження.
        /// </summary>
        public static string Researches {
            get {
                return ResourceManager.GetString("Researches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидання пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свій пароль.
        /// </summary>
        public static string ResetPasswordMsg {
            get {
                return ResourceManager.GetString("ResetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ролі.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Російська.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наука.
        /// </summary>
        public static string Science {
            get {
                return ResourceManager.GetString("Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукові зв&apos;язки.
        /// </summary>
        public static string ScienceConnections {
            get {
                return ResourceManager.GetString("ScienceConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукові напрями.
        /// </summary>
        public static string ScienceFields {
            get {
                return ResourceManager.GetString("ScienceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наукові інтереси.
        /// </summary>
        public static string ScienceInterests {
            get {
                return ResourceManager.GetString("ScienceInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити лист.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ми надіслали лист з підтвердженням на {0}. Будь ласка, дотримуйтесь інструкцій в листі..
        /// </summary>
        public static string SendVerificationEmailMsg {
            get {
                return ResourceManager.GetString("SendVerificationEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допоміжний персонал.
        /// </summary>
        public static string ServicePersonell {
            get {
                return ResourceManager.GetString("ServicePersonell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розклад сессії.
        /// </summary>
        public static string SessionSchedule {
            get {
                return ResourceManager.GetString("SessionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слаг.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слаг є частиною URL, який ідентифікує сторінки за допомогою легких для читання ключових слів..
        /// </summary>
        public static string SlugHelpText {
            get {
                return ResourceManager.GetString("SlugHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соціальні посилання.
        /// </summary>
        public static string SocialLinks {
            get {
                return ResourceManager.GetString("SocialLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спеціальності.
        /// </summary>
        public static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трасування стека.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студмісто НТУУ &quot;КПІ&quot;.
        /// </summary>
        public static string StudentCity {
            get {
                return ResourceManager.GetString("StudentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студентські організації та медіа ресурси.
        /// </summary>
        public static string StudentOrganizations {
            get {
                return ResourceManager.GetString("StudentOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг студентів.
        /// </summary>
        public static string StudentRating {
            get {
                return ResourceManager.GetString("StudentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студентська наука.
        /// </summary>
        public static string StudentResearches {
            get {
                return ResourceManager.GetString("StudentResearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця облікових записів.
        /// </summary>
        public static string TableOfAccounts {
            get {
                return ResourceManager.GetString("TableOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця робітників.
        /// </summary>
        public static string TableOfEmployees {
            get {
                return ResourceManager.GetString("TableOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця подій.
        /// </summary>
        public static string TableOfEvent {
            get {
                return ResourceManager.GetString("TableOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця новин.
        /// </summary>
        public static string TableOfNews {
            get {
                return ResourceManager.GetString("TableOfNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця викладачів.
        /// </summary>
        public static string TableOfTeachers {
            get {
                return ResourceManager.GetString("TableOfTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиці.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач відсутій.
        /// </summary>
        public static string TeacherAbsent {
            get {
                return ResourceManager.GetString("TeacherAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач з ім&apos;ям &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string TeacherCreatedMsg {
            get {
                return ResourceManager.GetString("TeacherCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач з ім&apos;ям &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string TeacherDeletedMsg {
            get {
                return ResourceManager.GetString("TeacherDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладачі.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач з ім&apos;ям &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string TeacherSavedMsg {
            get {
                return ResourceManager.GetString("TeacherSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Педагогічний склад.
        /// </summary>
        public static string TeachingStaff {
            get {
                return ResourceManager.GetString("TeachingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовий діапазон.
        /// </summary>
        public static string TimeRange {
            get {
                return ResourceManager.GetString("TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bundles/tinymce-uk.
        /// </summary>
        public static string tinymcePath {
            get {
                return ResourceManager.GetString("tinymcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter URL-адреса.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string Uncos {
            get {
                return ResourceManager.GetString("Uncos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка знаходиться в розробці.
        /// </summary>
        public static string Undone {
            get {
                return ResourceManager.GetString("Undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити електронну пошту.
        /// </summary>
        public static string UpdateEmail {
            get {
                return ResourceManager.GetString("UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити пароль.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновити ім&apos;я користувача.
        /// </summary>
        public static string UpdateUserName {
            get {
                return ResourceManager.GetString("UpdateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити нову картинку.
        /// </summary>
        public static string UploadNewImage {
            get {
                return ResourceManager.GetString("UploadNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити нову фотографію.
        /// </summary>
        public static string UploadNewPhoto {
            get {
                return ResourceManager.GetString("UploadNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корисні посилання.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач &quot;{0}&quot; успішно створений..
        /// </summary>
        public static string UserCreatedMsg {
            get {
                return ResourceManager.GetString("UserCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач &quot;{0}&quot; успішно видалений..
        /// </summary>
        public static string UserDeletedMsg {
            get {
                return ResourceManager.GetString("UserDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таке ім&apos;я користувача вже існує. Будь ласка, введіть інше ім&apos;я..
        /// </summary>
        public static string UserNameExistErrMsg {
            get {
                return ResourceManager.GetString("UserNameExistErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача не змінено. Не можна використовувати ваше поточне ім&apos;я користувача для його зміни..
        /// </summary>
        public static string UserNameNotChangedErrMsg {
            get {
                return ResourceManager.GetString("UserNameNotChangedErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з індифікатором = {0} не знайдений..
        /// </summary>
        public static string UserNoFound {
            get {
                return ResourceManager.GetString("UserNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач &quot;{0}&quot; успішно збережений..
        /// </summary>
        public static string UserSavedMsg {
            get {
                return ResourceManager.GetString("UserSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версія.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вконтакті URL-адреса.
        /// </summary>
        public static string VkontakteUrl {
            get {
                return ResourceManager.GetString("VkontakteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
